
import {Providers} from "./providers";
import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({children}) {
  return (
    <html lang="en" className='bg-gray-100'>
      <body className="bg-gray-100">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}